### ISSUE TITLE
MOJO-2014 IT test fails

### ISSUE THREAD

**Issue by puntogil** [mojohaus/templating-maven-plugin#11] opened 2016-02-16 17:33 UTC
Hi
I'm getting (templating-maven-plugin-1.0.0):
[INFO] Building: MOJO-2014/pom.xml
[INFO] run script verify.groovy
[INFO] ..FAILED (5.6 s)
[INFO]   The post-build script did not succeed. assert javaClass.text.contains('public static final String FIRST_COLOR = "red"')
       |         |    |
       |         |    false
       |         package org.codehaus.mojo.templating.it;
       |          
       |         public class Colors {
       |          
       |                public static final String FIRST_COLOR = "${first-color}";
       |                public static final String SECOND_COLOR = "${second-color}";
       |                public static final String THIRD_COLOR = "${third-color}";
       |         }
       /home/gil/rpmbuild/BUILD/templating-maven-plugin-1.0.0/target/it/MOJO-2014/target/generated-sources/java-templates/org/codehaus/mojo/templating/it/Colors.java

Environment:
Apache Maven 3.3.3 (NON-CANONICAL_2015-07-10T12:37:52_mockbuild; 2015-07-10T14:37:52+02:00)
Maven home: /usr/share/maven
Java version: 1.8.0_71, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.71-1.b15.fc23.i386/jre
Default locale: it_IT, platform encoding: UTF-8
OS name: "linux", version: "4.3.5-300.fc23.i686", arch: "i386", family: "unix"

Any ideas as to why?
Thanks in advance
Regards

**Comment by khmarbaise** [comment] 2016-02-16 21:50
Can you explain what kind of version of Maven you are using (where it is coming from?), cause this version is not the official Apache Maven version....Apart from that i have checked with the official Apache Maven Build
```
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /usr/share/maven
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.8.5", arch: "x86_64", family: "mac"
```
Furthermore i can't reproduce this problem...

**Comment by puntogil** [comment] 2016-02-16 22:15
Hi
its part of Fedora [1] distribution
all libraries and programs we use are built [2] and integrated with our tool, Mock [3]
other than that, in my opinion, it seems that it can depend on the JDK used (i / we use OpenJDK, vs. your Oracle JDK)
Regards
[1] https://fedoraproject.org/wiki/Overview
[2] https://fedoraproject.org/wiki/Packaging:Guidelines ; 
     https://fedoraproject.org/wiki/Packaging:Guidelines#No_inclusion_of_pre-built_binaries_or_libraries
[3] https://fedoraproject.org/wiki/Mock

**Comment by khmarbaise** [comment] 2016-02-16 22:20
The difference OpenJDK / Oracle JDK could be the root cause of that?

**Comment by puntogil** [comment] 2016-02-16 22:23
In some cases ... , Oracle JDK mask ertain problems however come out using OpenJDK

**Comment by khmarbaise** [comment] 2016-02-16 22:45
I have added openJDK 8 to the configuration for the CI build...lets see if we can reproduce it...

**Comment by khmarbaise** [comment] 2016-02-20 20:53
Can you please do the following on the checked out folder (templating-maven-plugin-1.0.0)...go to folder src/it/MOJO-2014/ and add the following file `invoker.properties` with the following content:
```
invoker.debug = true
``` 
and rerun the build which has failed...and attach the resulting `build.log` from the `target/it/MOJO-2014/build.log` to this issue...

Thanks...

**Comment by puntogil** [comment] 2016-02-20 21:57
[build.log.zip](https://github.com/mojohaus/templating-maven-plugin/files/139366/build.log.zip)
Done

**Comment by khmarbaise** [comment] 2016-02-20 22:27
So after taking a deeper look into your log file i've got the impression there is going something wrong...
I found something like this:
````
[DEBUG] org.codehaus.mojo.templating.it:mojo-2014:jar:0.0.1-SNAPSHOT
[INFO] 
[INFO] --- templating-maven-plugin:1.0-alpha-3:filter-sources (filter-src) @ mojo-2014 ---
[DEBUG] Trying to resolve artifact org.codehaus.mojo:templating-maven-plugin:pom:1.0.0
[DEBUG] Artifact org.codehaus.mojo:templating-maven-plugin:pom:1.0.0 was resolved to /tmp/xmvn-1144991498662096713/xmvn-92ad1f8a-1517-4103-b95e-53f1bd2ca94c7606445630992061253/templating-maven-plugin-1.0.0.pom
[DEBUG] Trying to resolve artifact org.apache.maven:maven-model:pom:3.2.5
[DEBUG] Artifact org.apache.maven:maven-model:pom:3.2.5 was resolved to /tmp/xmvn-1144991498662096713/xmvn-1549f685-fd63-46e9-a767-e3d08e734e983872642958665769520/maven-model-3.2.5.pom
[DEBUG] Trying to resolve artifact org.codehaus.plexus:plexus-utils:pom:3.0.20
``` 

The line `[INFO] --- templating-maven-plugin:1.0-alpha-3:filter-sources (filter-src) @ mojo-2014 ---` like this shows me there is something wrong...How have you started the whole build:

via `mvn -Prun-its clean verify` from the root of the project...

I have found several appearance of the wrong number of the templating-maven-plugin..it should be 1.0.0 but it is '1.0-alpha-3' ...in your log example...
``` 
[DEBUG] Configuring mojo org.codehaus.mojo:templating-maven-plugin:1.0-alpha-3:filter-sources from plugin realm ClassRealm[plugin>org.codehaus.mojo:templating-maven-plugin:1.0.0, parent: sun.misc.Launcher$AppClassLoader@25154f]
[DEBUG] Configuring mojo 'org.codehaus.mojo:templating-maven-plugin:1.0-alpha-3:filter-sources' with basic configurator -->
[DEBUG]   (f) outputDirectory = /home/gil/rpmbuild/BUILD/templating-maven-plugin-1.0.0/target/it/MOJO-2014/target/generated-sources/java-templates
[DEBUG]   (f) project = MavenProject: org.codehaus.mojo.templating.it:mojo-2014
``` 

Furthermore you seemed to be having some kind of extension installed:

```
[DEBUG] Full XMvn dependency report:
[DEBUG] <gId>:<aId>:<ext>[:<classifier>:]<version> => <compat-version>, provided by <pkg-name> (<rpm-version>)
[DEBUG]   org.codehaus.mojo:templating-maven-plugin:pom:1.0.0 => null, provided by (none)
[DEBUG]   org.codehaus.mojo:templating-maven-plugin:jar:1.0.0 => null, provided by templating-maven-plugin (1.0)
[DEBUG]   org.apache.maven.plugins:maven-resources-plugin:pom:2.6 => null, provided by (none)
```

I assume that the pom file in the `target/it/MOJO-2014` folder looks exactly like this:
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.codehaus.mojo.templating.it</groupId>
  <artifactId>mojo-2014</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <description>MOJO-2014</description>
  <build>
    <filters>
      <filter>colors.properties</filter>
    </filters>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>templating-maven-plugin</artifactId>
        <version>1.0.0</version>
        <executions>
          <execution>
            <id>filter-src</id>
            <goals>
              <goal>filter-sources</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
```

Can you check this...

**Comment by puntogil** [comment] 2016-02-20 23:19
the pom file have org.codehaus.mojo:templating-maven-plugin:1.0.0 but is in used the old org.codehaus.mojo:templating-maven-plugin:1.0-alpha-3 if is installed. If i uninstall 1.0-alpha-3
the build ends successfully.
thanks

**Comment by puntogil** [comment] 2016-02-20 23:26
We use https://mizdebsk.fedorapeople.org/xmvn/site/ as maven extension
because of this rule: https://fedoraproject.org/wiki/Packaging:Guidelines#No_inclusion_of_pre-built_binaries_or_libraries

**Comment by khmarbaise** [comment] 2016-02-20 23:40
If the pom file references 1.0.0 this version must be used...it does not matter if it is installed an other version...cause these are integration tests which must be reliable onto the given version which is tested...So i don't understand your expression: 'if is installed' cause the version will be installed by the maven-invoker-plugin into the repo in `target/loca-repo/`...

**Closed** 2016-02-22 19:41 UTC
Labels: invalid

**Comment by puntogil** [comment] 2016-02-22 20:04
We usually import, * always *, latest version / release of each software. For this reason, with the exception of some cases, the extension Maven * ignores * the version of dependencies and plugins used during the construction of a project
Sorry for the delay in answering
Again thanks
Regards
